### ISSUE TITLE
Extension is not working - does not display badge

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [Seer-Software-Dev/flarum-verified-badge#1]
On my testing forum I enabled this extension and set it up exactly how your Discuss post said. After refreshing and going to my user profile, the badge was fully transparent without the "badge" part.

Image 1: https://imgur.com/a/Z4vL5Wp

Image 2: https://imgur.com/a/o23IDzd

Image 3: https://imgur.com/a/unzEmdI

**Comment by ThatKoffe** [comment]
Hey @Kaleb99jOfficial thanks for using this plugin!

Could you please check the console for any errors relating to this issue?
I'd love to hear from you soon!

**Comment by Kaleb99jOfficial** [comment]
@Serakoi My testing server (Raspberry Pi) corrupted the SD Card so I am unable to provide logs from now. I will re-install Flarum on another card later and try it again.

**Comment by ThatKoffe** [comment]
> @Serakoi My testing server (Raspberry Pi) corrupted the SD Card so I am unable to provide logs from now. I will re-install Flarum on another card later and try it again.

That'd be great!

**Comment by Kaleb99jOfficial** [comment]
@Serakoi I am unable to get Apache working on my RPi. I will install Flarum to my VPS and try there.

**Comment by Kaleb99jOfficial** [comment]
I do not know what I have done differently but it is now working. I speculate that maybe there was a Flarum dependency that wasn't installed before and that broke it? I can see that others are having issues so I will leave this open.

**Comment by ThatKoffe** [comment]
> I do not know what I have done differently but it is now working. I speculate that maybe there was a Flarum dependency that wasn't installed before and that broke it? I can see that others are having issues so I will leave this open.

Ah okay! Well thanks for your confirmation!
Love to hear from you soon!

**Comment by Kaleb99jOfficial** [comment]
Well, this is old, and I forgot about it. I just looked and my testing forum is still up and the extension still works. I will be closing this now.

**Comment by ThatKoffe** [comment]
> 

Good to know! Sorry for not looking into it quicker
